### ISSUE TITLE
How can I build boinc for termux?

### ISSUE THREAD

**Issue by juanro49** [truboxl/boinc-termux-client#1]
Hi, how could I compile the boinc client to use it in termux? I tried with this guide to compile the boinc client for Android https://github.com/truboxl/boinc-android but when I run it, I get errors from the ssl requests and at the end it closes with the message "Suspending computation - GUI not active"

For the moment I'm using the boinc termux package, but it doesn't allow to edit some files like for example client_state.xml to edit the field <domain_name>

**Comment by truboxl** [comment]
Hi and thanks for checking out my guide. :)

https://github.com/truboxl/boinc-android is intended for use on a PC to build BOINC for Android app. The "Suspending computation - GUI not active" is normal because the BOINC source code treats building the Android version differently and the resulting client requires Java GUI to interact, controlled by `-DANDROID`. I am not sure about the SSL problem though.

To be able to build BOINC on Termux, you can check out Termux's build script for reference and include their patches at https://github.com/termux/termux-packages/tree/master/packages/boinc

client_state.xml is normally not intended for edit as its used solely by BOINC client to store information. If you want to edit the device name, for example changing `localhost` to something else, you may need to build the client from the BOINC master branch as it includes the feature recently. https://github.com/BOINC/boinc/pull/3620

**Comment by juanro49** [comment]
> Hi and thanks for checking out my guide. :)
> 
> https://github.com/truboxl/boinc-android is intended for use on a PC to build BOINC for Android app. The "Suspending computation - GUI not active" is normal because the BOINC source code treats building the Android version differently and the resulting client requires Java GUI to interact, controlled by `-DANDROID`. I am not sure about the SSL problem though.
> 
> To be able to build BOINC on Termux, you can check out Termux's build script for reference and include their patches at https://github.com/termux/termux-packages/tree/master/packages/boinc
> 
> client_state.xml is normally not intended for edit as its used solely by BOINC client to store information. If you want to edit the device name, for example changing `localhost` to something else, you may need to build the client from the BOINC master branch as it includes the feature recently. [BOINC/boinc#3620](https://github.com/BOINC/boinc/pull/3620)

Thanks, I follow the steps in this url https://github.com/termux/termux-packages/wiki/Building-packages and I build boinc 7.17.0 sucessfully for termux, I fixed the boinc platform and some other changes and now I can change domain name 

```ERMUX_PKG_HOMEPAGE=https://boinc.berkeley.edu/
TERMUX_PKG_DESCRIPTION="Open-source software for volunteer computing"
TERMUX_PKG_LICENSE="GPL-3.0"
_MAJOR_VERSION=7.17
TERMUX_PKG_VERSION=${_MAJOR_VERSION}.0
TERMUX_PKG_REVISION=2
TERMUX_PKG_SRCURL=https://github.com/BOINC/boinc/archive/master.tar.gz
TERMUX_PKG_SHA256=deb6b853ada2c8ecdfd8521ea066a718e1dafc6107f9ec742e6b1328744f60a9
TERMUX_PKG_DEPENDS="libandroid-shmem, libc++, libcurl, openssl, zlib"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_NO_STATICSPLIT=true

TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
--with-boinc-platform="aarch64-android-linux-gnu"
--with-boinc-alt-platform="arm-android-linux-gnu"
--disable-server
--enable-client
--disable-manager
--disable-shared
--enable-static
"

TERMUX_PKG_CONFFILES="etc/boinc-client.conf"

termux_step_pre_configure() {
        LDFLAGS+=" -L$PREFIX/lib -landroid-shmem -static-libstdc++ -Qunused-arguments -fuse-ld=lld"
        CFLAGS+=" -O3 -march=armv8.5-a+crypto+simd+sve2-sha3+sve2-aes+sve2-sm4+memtag+rng+sm4+sha3 -mtune=cortex-a53"
        CXXFLAGS+=" -O3 -march=armv8.5-a+crypto+simd+sve2-sha3+sve2-aes+sve2-sm4+memtag+rng+sm4+sha3 -mtune=cortex-a53"
        ./_autosetup
}```

**Comment by truboxl** [comment]
I think I will close this issue now.

BOINC has released a new version of client app through their website and FDroid store. You can use that if you find that more convenient.
https://boinc.berkeley.edu/download_all.php
https://f-droid.org/en/packages/edu.berkeley.boinc/

I also tested and patched the BOINC package over Termux repo that works for majority of the devices on Termux.
It also should follow more closely with upstream now.
I may sometime cherry pick some patches from upstream to improve BOINC on Termux.

As you already know it works more like Linux version rather than Android version and doesn't integrate with Termux API for temperature sensing. For that, you need the support scripts which you can check out over at `sh/` folder

`start-boinc`, `config-boinc` and `monitor-boinc` should be sufficient
https://github.com/truboxl/boinc-termux-client/tree/master/sh

Feel free to submit patches at Termux-packages for improvement.
https://github.com/termux/termux-packages/tree/master/packages/boinc
